version: '3.8'

services:
  service1:
    build: ./service1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:8081"  # NGINX port exposed outside
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd  # Mount .htpasswd
      - ./nginx/index.html:/usr/share/nginx/html/index.html  # Mount index.html
    depends_on:
      - service1
      - service2
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
