version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - mynetwork

  service1:
    build: ./service1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    networks:
      - mynetwork

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8198:8198"
      - "8197:8197"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - service1
      - service2
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge