version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - mynetwork

  service1:
    build: ./service1
    depends_on:
      - redis
    networks:
      - mynetwork
    volumes:
      - ./service1:/app
      - ./tests:/app/tests

  service2:
    build: ./service2
    container_name: service2
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8197:8197"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
