version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - mynetwork

  service1:
    build:
      context: ./service1
    container_name: service1
    depends_on:
      - redis
    networks:
      - mynetwork
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./service1:/app
      - ./tests:/app/tests
    command: ["python3", "/app/app.py"]

  service2:
    build:
      context: ./service2
    container_name: service2
    networks:
      - mynetwork
    command: ["node", "/app/app.js"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8197:80" # Map port 80 inside nginx to 8197 on the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
