version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:7.4
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  service1:
    build: ./service1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8198:80"
    depends_on:
      - service1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
